name: Use repoman to check this
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'metadata/**'
    types: [opened, edited, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the base ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Checkout the head ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Show
        run: git show-ref
        run: git diff --raw master
