name: Use repoman to check this
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'metadata/**'
    types: [opened, edited, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code -- master
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Checkout repository code -- HEAD
        uses: actions/checkout@v2
        with:
          ref: HEAD
          path: HEAD
      - name: Show git log -- master
        run: cd ~/master && git log
      - name: Show git log -- HEAD
        run: cd ~/HEAD && git log
