name: Use repoman to check this
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'metadata/**'
    types: [opened, edited, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request HEAD
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.base_ref }}
      - name: Show
        run: git show-ref
