name: Use repoman to check this
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'metadata/**'
    types: [opened, edited, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: |
          set -xe
          mkdir -p /var/db/repos/gentoo{,-zh}
          mkdir -p /var/tmp/portage
      - name: Checkout the base ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: /var/db/repos/gentoo-zh
      - name: Checkout the head ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: /var/db/repos/gentoo-zh
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends libxslt-dev libxml2-dev libxml2-utils zstd python3-lxml
      - name: Fetch ::gentoo repo
        uses: actions/checkout@v2
        with:
          repository: gentoo-mirror/gentoo
          path: /var/db/repos/gentoo
      - name: Fetch portage
        uses: actions/checkout@v2
        with:
          repository: gentoo/portage
      - name: Install portage
        run: |
          set -xe
          printf "[build_ext]\nportage-ext-modules=true" >>setup.cfg
          ./setup.py install --prefix=/usr
          echo 'portage:x:250:250:portage:/var/tmp/portage:/bin/false' >>/etc/passwd
          echo 'portage::250:portage' >>/etc/group
          ln -s /var/db/repos/gentoo/profiles/default/linux/amd64/17.1 /etc/portage/make.profile
          printf "[gentoo-zh]\nlocation = /var/db/repos/gentoo-zh" >>/etc/portage/repos.conf
      - name: Install repoman
        run: |
          set -xe
          cd repoman
          ./setup.py install --prefix=/usr
      - name: Test
        run: |
          cd /var/db/repos/gentoo-zh/app-office/wps-office
          repoman scan
