name: Use repoman to check this pr
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'metadata/**'
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Fetch gentoo-zh repo
        uses: actions/checkout@v2
        with:
          ref: ${GITHUB_REF}
          path: pr
      - name: Show
        run: tree .
